/* do not change this file, it is auto generated by storybook. */

import {
  configure,
  addDecorator,
  addParameters,
} from '@storybook/react-native';

import { decorators, parameters } from './preview';

if (decorators) {
  decorators.forEach((decorator) => addDecorator(decorator));
}

if (parameters) {
  addParameters(parameters);
}

const getStories = () => {
  return [
    // Primitives
    require('../ui/primitives/Box.stories'),
    require('../ui/primitives/Text.stories'),
    require('../ui/primitives/Button.stories'),
    require('../ui/primitives/Input.stories'),
    require('../ui/primitives/Card.stories'),
    require('../ui/primitives/Panel.stories'),
    require('../ui/primitives/Tag.stories'),
    require('../ui/primitives/Avatar.stories'),
    require('../ui/primitives/Divider.stories'),
    require('../ui/primitives/Surface.stories'),
    require('../ui/primitives/Modal.stories'),
    
    // Components
    require('../ui/components/MatchCard.stories'),
    require('../ui/components/TournamentHeader.stories'),
    require('../ui/components/FeatureCard.stories'),
    require('../ui/components/StatCard.stories'),
  ];
};

configure(getStories, module, false);

export const view = { getStorybookUI: () => null };
